/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectwithgui;

/**
 *
 * @author Reyan Sheikh
 */
public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        selectarea = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        rate = new javax.swing.JButton();
        near = new javax.swing.JButton();
        path = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 520));

        Heading.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("HOSPITAL LOCATOR");

        selectarea.setFont(new java.awt.Font("Bebas", 0, 18)); // NOI18N
        selectarea.setText("Select area");

        area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gulshan e Iqbal", "PECHS", "Clifton", "Bahadrabad" }));
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        rate.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        rate.setText("Highest rated");
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });

        near.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        near.setText("Nearest");
        near.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearActionPerformed(evt);
            }
        });

        path.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        path.setText("Path Finder");
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectarea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(near, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectarea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rate)
                    .addComponent(near)
                    .addComponent(path))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        // TODO add your handling code here:
      
        List list = new List();
        list.InsertInOrderdistance("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8);
        list.InsertInOrderdistance("Ibn-Sina Hosptical", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2);
        list.InsertInOrderdistance("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3);
        list.InsertInOrderdistance("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17);
        list.InsertInOrderdistance("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4);
        list.InsertInOrderdistance("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5);
        list.InsertInOrderdistance("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4);

        AreaArray arr = new AreaArray();

        Graph g = new Graph(6);
        g.AddVertex(new vertex("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8)); // v0
        g.AddVertex(new vertex("Ibn-Sina Hospital", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2)); // v1
        g.AddVertex(new vertex("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3)); // v2
        g.AddVertex(new vertex("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17)); // v3
        g.AddVertex(new vertex("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4)); // v4
        g.AddVertex(new vertex("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5));// v5
        g.AddVertex(new vertex("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4));// v5

        g.AddEdge(g.AdjList.get(0), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(3));
        g.AddEdge(g.AdjList.get(3), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(3));

        arr.AddData("Gulshan", list, g);
        
        
        List PECHSlist = new List();
        PECHSlist.InsertInOrderdistance("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8);
        PECHSlist.InsertInOrderdistance("Karim Clinic", "NOT ENTERED", 4.5, 3.2);
        PECHSlist.InsertInOrderdistance("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2);
        PECHSlist.InsertInOrderdistance("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9);
        PECHSlist.InsertInOrderdistance("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2);

        Graph PECHSgraph = new Graph(15);
        PECHSgraph.AddVertex(new vertex("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8));//v0
        PECHSgraph.AddVertex(new vertex("Karim Clinic", "NOT ENTERED", 4.5, 3.7));//v1
        PECHSgraph.AddVertex(new vertex("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2)); //v2
        PECHSgraph.AddVertex(new vertex("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9)); //v3
        PECHSgraph.AddVertex(new vertex("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2)); //v4

        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(3), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(3));

        arr.AddData("PECHS", PECHSlist, PECHSgraph);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        int x = area.getSelectedIndex();
        display.setVisible(false);
        if (x==0) {
            display.setText(list.toString());
            display.setVisible(true);
        }
        if (x==1) {
            display.setText(PECHSlist.toString());
               display.setVisible(true);
        }
    }//GEN-LAST:event_areaActionPerformed

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
         List list = new List();
        list.InsertInOrder("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8);
        list.InsertInOrder("Ibn-Sina Hosptical", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2);
        list.InsertInOrder("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3);
        list.InsertInOrder("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17);
        list.InsertInOrder("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4);
        list.InsertInOrder("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5);
        list.InsertInOrder("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4);

        AreaArray arr = new AreaArray();

        Graph g = new Graph(6);
        g.AddVertex(new vertex("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8)); // v0
        g.AddVertex(new vertex("Ibn-Sina Hospital", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2)); // v1
        g.AddVertex(new vertex("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3)); // v2
        g.AddVertex(new vertex("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17)); // v3
        g.AddVertex(new vertex("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4)); // v4
        g.AddVertex(new vertex("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5));// v5
        g.AddVertex(new vertex("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4));// v5

        g.AddEdge(g.AdjList.get(0), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(3));
        g.AddEdge(g.AdjList.get(3), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(3));

        arr.AddData("Gulshan", list, g);
        
        
        List PECHSlist = new List();
        PECHSlist.InsertInOrder("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8);
        PECHSlist.InsertInOrder("Karim Clinic", "NOT ENTERED", 4.5, 3.2);
        PECHSlist.InsertInOrder("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2);
        PECHSlist.InsertInOrder("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9);
        PECHSlist.InsertInOrder("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2);

        Graph PECHSgraph = new Graph(15);
        PECHSgraph.AddVertex(new vertex("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8));//v0
        PECHSgraph.AddVertex(new vertex("Karim Clinic", "NOT ENTERED", 4.5, 3.7));//v1
        PECHSgraph.AddVertex(new vertex("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2)); //v2
        PECHSgraph.AddVertex(new vertex("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9)); //v3
        PECHSgraph.AddVertex(new vertex("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2)); //v4

        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(3), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(3));

        arr.AddData("PECHS", PECHSlist, PECHSgraph);
        
        int x = area.getSelectedIndex();
        if (x==0) {
            display.setText(list.Tail.getData());
            display.setVisible(true);
        }
        if (x==1) {
            display.setText(PECHSlist.Tail.getData());
        }
    }//GEN-LAST:event_rateActionPerformed

    private void nearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearActionPerformed
        // TODO add your handling code here:
          List list = new List();
        list.InsertInOrderdistance("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8);
        list.InsertInOrderdistance("Ibn-Sina Hosptical", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2);
        list.InsertInOrderdistance("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3);
        list.InsertInOrderdistance("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17);
        list.InsertInOrderdistance("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4);
        list.InsertInOrderdistance("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5);
        list.InsertInOrderdistance("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4);

        AreaArray arr = new AreaArray();

        Graph g = new Graph(6);
        g.AddVertex(new vertex("Patel Hospital", "ST-18, Block-4, Gulshan-e-Iqbal,Karachi - 75300, Pakistan.، Karachi, Pakistan", 3.6, 5.8)); // v0
        g.AddVertex(new vertex("Ibn-Sina Hospital", "St-22-B,, University Rd, Block 6, Gulshan-e-Iqbal, Sindh، Karachi, Pakistan", 3.8, 4.2)); // v1
        g.AddVertex(new vertex("Samdani Hospital", "a 560 block, Street No 5, Karachi, Pakistan", 2.3, 5.3)); // v2
        g.AddVertex(new vertex("AL Mustafa Medical", "ST-1 Block 13-C Gulshan-e-Iqbal، University Road، Karachi, Pakistan", 4.1, 17)); // v3
        g.AddVertex(new vertex("Haji Rang Elahi Hospital", "St 4B, Block-4, Gulshan E Iqbal, Karachi, Karachi, Pakistan", 4.6, 5.4)); // v4
        g.AddVertex(new vertex("NIBD Hospital", "Gulshan-e-Iqbal, Karachi, Pakistan", 4.2, 7.5));// v5
        g.AddVertex(new vertex("T.O Clinic Hospital", "no, Street 1, Karachi, Pakistan", 3.1, 5.4));// v5

        g.AddEdge(g.AdjList.get(0), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(0), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(1));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(2));
        g.AddEdge(g.AdjList.get(1), g.AdjList.get(0));
        g.AddEdge(g.AdjList.get(2), g.AdjList.get(3));
        g.AddEdge(g.AdjList.get(3), g.AdjList.get(4));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(5));
        g.AddEdge(g.AdjList.get(4), g.AdjList.get(3));

        arr.AddData("Gulshan", list, g);
        
        
        List PECHSlist = new List();
        PECHSlist.InsertInOrderdistance("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8);
        PECHSlist.InsertInOrderdistance("Karim Clinic", "NOT ENTERED", 4.5, 3.2);
        PECHSlist.InsertInOrderdistance("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2);
        PECHSlist.InsertInOrderdistance("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9);
        PECHSlist.InsertInOrderdistance("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2);

        Graph PECHSgraph = new Graph(15);
        PECHSgraph.AddVertex(new vertex("Shehroz Medical Centre", "NOT ENTERED", 3.6, 5.8));//v0
        PECHSgraph.AddVertex(new vertex("Karim Clinic", "NOT ENTERED", 4.5, 3.7));//v1
        PECHSgraph.AddVertex(new vertex("Gupta Memorial Hospital", "NOT ENTERED", 3.8, 7.2)); //v2
        PECHSgraph.AddVertex(new vertex("Aisha's Dental Clinic", "NOT ENTERED", 4.1, 1.9)); //v3
        PECHSgraph.AddVertex(new vertex("Asghar National Hospital", "NOT ENTERED", 3.2, 4.2)); //v4

        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(0), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(1), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(3));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(2), PECHSgraph.AdjList.get(1));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(3), PECHSgraph.AdjList.get(4));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(2));
        PECHSgraph.AddEdge(PECHSgraph.AdjList.get(4), PECHSgraph.AdjList.get(3));

        arr.AddData("PECHS", PECHSlist, PECHSgraph);
        
        
        int x = area.getSelectedIndex();
        if (x==0) {
            display.setText(list.Tail.getData());
            display.setVisible(true);
        }
        if (x==1) {
            display.setText(PECHSlist.Tail.getData());
        }
          
    }//GEN-LAST:event_nearActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
       PathFinder p = new PathFinder();
       p.setVisible(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JComboBox<String> area;
    private javax.swing.JTextArea display;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton near;
    private javax.swing.JButton path;
    private javax.swing.JButton rate;
    private javax.swing.JLabel selectarea;
    // End of variables declaration//GEN-END:variables
}
